---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/pages
  label: About
  create: documents
  match: "**/*"
- type: directory
  path: src/content/posts
  label: News
  create: documents
  match: "**/*"
upload_dir: public/media
public_path: "/static/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: out
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
