---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: file
  name: image
  label: image
- name: link
  type: text
  config:
    required: false
  label: link
  description: Instagram link or something. Opens in a new tab when project is clicked.
